config/routes.rb
Rails.application.routes.draw do
	
  get 'braintree/new'

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    resources :listings, only: [:index, :new, :create]
  end

    resources :listings, only: [:show, :edit, :update, :destroy]

  root to: "welcomes#index"	
  resources :welcomes, only: [:index]

  post 'braintree/checkout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :listings
  include Clearance::User
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
  	 @client_token = Braintree::ClientToken.generate
  end

    def checkout
	  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

	  result = Braintree::Transaction.sale(
	   :amount => "9000.00", #this is currently hardcoded
	   :payment_method_nonce => nonce_from_the_client,
	   :options => {
	      :submit_for_settlement => true
	    }
	   )

	  if result.success?
	    redirect_to :root, :flash => { :success => "Transaction successful!" }
	  else
	    redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
	  end 
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listings
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET users/1/listings
  def index
    @listings = @user.listings
  end

  # GET users/1/listings/1
  def show
  end

  # GET users/1/listings/new
  def new
    @listing = @user.listings.build
  end

  # GET users/1/listings/1/edit
  def edit
  end

  # POST users/1/listings
  def create
    @listing = @user.listings.build(listing_params)

    if @listing.save
      redirect_to([@listing.user, @listing], notice: 'Listing was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT users/1/listings/1
  def update
    if @listing.update_attributes(listing_params)
      redirect_to([@listing.user, @listing], notice: 'Listing was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE users/1/listings/1
  def destroy
    @listing.destroy

    redirect_to user_listings_url(@user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listings
      @user = User.find(params[:user_id])
    end

    def set_listing
      @listing = @user.listings.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def listing_params
      params.require(:listing).permit(:name, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
    
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :require_login
 
  # GET /welcomes
  # GET /welcomes.json
  def index
    
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/braintree/new.html.erb
    <div class="demo-frame">  

      <%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %>

        <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
        <div id="card-number" class="hosted-field"></div>

        <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>      
        <div id="expiration-date" class="hosted-field"></div>

        <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
        <div id="cvv" class="hosted-field"></div>

        <%= form.hidden_field "payment_method_nonce" %>

        <div class="button-container">
          <%= form.submit "Purchase", disabled: true, class: "btn btn-primary button", id: "submit-payment-btn" %>
        </div>
      <% end %>
    </div>

    <!-- Load the Client component. -->
    <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

    <!-- Load the Hosted Fields component. -->
    <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>


    <script>
    $(document).ready(function(){

      var authorization = '<%= @client_token %>'
      var submit = document.querySelector('#submit-payment-btn');
      var form = document.querySelector('#cardForm');
      

      braintree.client.create({
        // Replace this with your own authorization.
        authorization
      }, function (clientErr, clientInstance) {
        if (clientErr) {
          // Handle error in client creation
          return;
        }

        braintree.hostedFields.create({
          client: clientInstance,
          styles: {
            'input': {
              'font-size': '14pt'
            },
            'input.invalid': {
              'color': 'red'
            },
            'input.valid': {
              'color': 'green'
            }
          },
          fields: {
            number: {
              selector: '#card-number',
              placeholder: '4111 1111 1111 1111'
            },
            cvv: {
              selector: '#cvv',
              placeholder: '123'
            },
            expirationDate: {
              selector: '#expiration-date',
              placeholder: '10/2019'
            }
          }
        }, function (hostedFieldsErr, hostedFieldsInstance) {
          if (hostedFieldsErr) {
            // Handle error in Hosted Fields creation
            return;
          }

          submit.removeAttribute('disabled');

          form.addEventListener('submit', function (event) {
            event.preventDefault();

            hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
              if (tokenizeErr) {
                // Handle error in Hosted Fields tokenization
                return;
              }

              // Put `payload.nonce` into the `payment_method_nonce` input, and then
              // submit the form. Alternatively, you could send the nonce to your server
              // with AJAX.
              document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
              form.submit();
            });
          }, false);
        });
      });



    });
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pabnb</title>
    <%= csrf_meta_tags %>


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <div>
  
  	<% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
  </div>


    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_for([@listing.user, @listing]) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', [@listing.user, @listing] %> |
<%= link_to 'Back', user_listings_path(@listing.user) %>

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @listings.each do |listing| %>
  <tr>
    <td><%= listing.name %></td>
    <td><%= listing.content %></td>
    <td><%= link_to 'Show', listing %></td>
    <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
    <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Listing', new_user_listing_path(params[:user_id]) %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', user_listings_path(@listing.user) %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @listing.name %>
</p>

<p>
  <b>Content:</b>
  <%= @listing.content %>
</p>


<%= link_to 'Edit', edit_user_listing_path(@listing.user, @listing) %> |
<%= link_to 'Back', user_listings_path(@listing.user) %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcomes/_form.html.erb
<%= form_for(welcome) do |f| %>
  <% if welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% welcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcomes</h1>


<%= link_to "Make Payment", braintree_new_path %>

app/views/welcomes/new.html.erb
<h1>New Welcome</h1>

<%= render 'form', welcome: @welcome %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>